### PR TITLE
RFC process

### PR DESCRIPTION
**Pull request by Razican**
[Rendered](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/master/text/0001-rfc-process.md)

This is the pull request for the first RFC of SUPER, the RFC process itself. This would implement [super/#38](https://github.com/SUPERAndroidAnalyzer/super/issues/38).

What do you think, @SUPERAndroidAnalyzer? we need everyone to be ok with this. Please, read all the documents perfectly and try to catch issues, errors or possible improvements.

### CODE REVIEW

**Comment by Razican** [comment]
Here, do you think that the _[When you need to follow this process](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/rfc-process/text/0000-rfc-process.md#when-you-need-to-follow-this-process)_ is good enough? I set up some cases which I think is fine, but I'm not sure if we could add more.

Also, we should discuss the [unresolved questions](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/rfc-process/text/0000-rfc-process.md#unresolved-questions). I'm against 3, and in favour of 2. I'm still not sure about 1, but maybe we could discuss it and see if we can simplify the process.

Another question is: we talk about stakeholders, which for now is only the four of us, but should we mantain that text just in case, for the future?

About [alternatives](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/rfc-process/text/0000-rfc-process.md#alternatives), I don't think that continuing our current process is good, since it doesn't give the potential community the posibility to give good feedback (we don't currently have a forum or anything). And I think that this RFC process is complex enough to think about other more complex options. I'm even thinking we could try to simplify this RFC a bit.

What do you think?

**Comment by Br1oP** [comment]
I agree with the RFC process. That being said, I think that we shouldn't totally stop the current issue based system. I agree that in the future we shouldn't continue this process, but for now I think it is alright since it is informal and we can keep track of developments and bugs very easily.

I think the RFC process will be a really nice add to the project as long as it is not overused, since it could be too formal for small things.

About the unanswered questions, I think that one of the improvements of this system is to resolve number 2, and I think it is also balanced so It also works for number 1.
About the number 3, why are you against @Razican ? I think it would be helpful to retain rejected RFCs, because by doing that we are letting other people who might have similar ideas find out why those ideas were rejected in the past.

I think the stakeholders thing doesn't really matter right now, we can keep the text but I don't see us using that atleast until we grow as a community.

**Comment by SergioD0l** [comment]
I agree with the RFC process too, about unresolved questions i think it's better for us to retain rejected RFCs as Bruno says, because it could avoid many questions of people that could have similar ideas in the future.

**Comment by Razican** [comment]
Hmm the thing is that the pull requests would still be stored as "closed", so we would still have that information available. I don't think we would need to store the RFCs themselves in the repo, it could lead to confussion: how do we label them?Where do we store them?

**Comment by Chuky9** [comment]
Sorry for this delayed answer. I find this RFC very interesting as it is enough explanatory as well as concise and detailed. It's a great oportunity to discuss with the community what we are planning to do in order to get more people involved or simple a way to record what we are deciding as a minute book of our meetings. 

Regarding to unresolved questions I agree with all of you specially in maintaining reject RFCs due to it could also help, not only to avoid other people to create new RFCs, to maintain an historic in order to implement or replan some features based on what are explained there.  @Razican  will people be able to access to closed PR to consult those RFCs before creating a new one? Is there any tag to identified "accepted" RFCs from "Rejected" ones?

One more think I would add to this process during the RFC creation is the fact that if the founder of the RFC wants to implement his/hers idea, a new comment should be add after oppening the PR indicanting that as well as a time estimation of its implementation (there is no need to be absolutly precise, it's just could help us to plan and discuss if we accept or reject it).

I agree with @Br1oP. We should mantain, at least for now, the issue process and parellely start this RFC process.

To round it all of, we should go on with this!

**Comment by Razican** [comment]
I will propose some changes to the RFC so that all the current comments are addressed:
- Add the following tags to RFC pull requests: `Active`, `Rejected`, `Implemented`, `P-low`, `P-medium` and `P-high`.
- The founder/creator of the pull request is encouraged to say if he/she is willing to implement the RFC.
- A closed pull request can only be closed with the `Active` or `Rejected` tag. If `Active`, it must also have one of the priority tags (the ones starting with P) indicating the implementation priority if the implementation will be done by our team.
- Once a RFC is closed as `active`, a tracking issue will be opened in the repo, to track the implementation of the RFC. The RFC must be updated with the tracking issue link.
- If the founder/creator of the RFC decides to implement it, the priority doesn't matter, and will be merged once the pull request in the respective repo is accepted. Aditional comments to the implementation will be done in the implementation pull request.
- Once the implementation pull request is merged in the code repo, the RFC must be updated with the pull request link, and the tracking issue must be closed. The `Active` tag is removed and the `Implemented` tag is added to the RFC pull request.

This enables us to search rejected RFCs in the pull requests list by searching `is:pr is:closed label:Rejected`, accepted/active but unimplemented pull requests by `is:pr is:closed label:Active` and implemented RFCs by searching for `is:pr is:closed label:Implemented`. This avoids adding rejected RFCs to the repo, which in turn makes the repo smaller and easier to understand, while still enabling rejected RFCs to be searched.

About continuing with the issue system, the RFC allows issues to be created for small things, which I think is what you mean, and also, once an RFC is accepted, a tracking issue will be created. If I misunderstand, please, explain.

What do you think? if you accept it, I'll add it to the RFC.

**Comment by Chuky9** [comment]
@Razican I'm fine with that changes!

**Comment by SergioD0l** [comment]
I agree with this changes!! @Razican

**Comment by Br1oP** [comment]
I accept the changes to the RFC.

**Comment by Razican** [comment]
I added commits with latest changes. Please, review them today or tomorrow as I will be merging the RFC on Monday. The [`README.md`](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/rfc-process/README.md) and the [`text/0000-rfc-process.md`](https://github.com/SUPERAndroidAnalyzer/rfcs/blob/rfc-process/text/0000-rfc-process.md) files have some sections in common, and they **must** have the same text.

Check also for typos.

**Pull request merged**
